
- name: install bc (CentOS)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  sudo: yes
  yum: pkg=bc state=installed

- name: install bc (Ubuntu)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  sudo: yes
  apt: pkg=bc state=installed