- name: install libffi (CentOS)
  yum: name='{{item}}' state=installed
  sudo: yes
  with_items:
    - libffi-devel
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: install libffi (Ubuntu)
  apt: pkg='{{item}}' state=latest
  sudo: yes
  with_items:
    - libffi6
    - libffi-dev 
    - libssl-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    

