- name: Add ppa:chris-lea/node.js repository
  apt_repository: repo='ppa:chris-lea/node.js'
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install nodejs
  apt: pkg={{item}} state=installed
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
    - build-essential
    - nodejs
    
- name: Install  npm
  apt: pkg=npm state=installed
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  #npm can throw errors if we're using https://launchpad.net/~chris-lea/+archive/ubuntu/node.js
  #as the PPA, so just ignore them
  ignore_errors: yes
  
