
- name: install vim (CentOS)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  sudo: yes
  yum: pkg=vim state=installed

- name: install vim (Ubuntu)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  sudo: yes
  apt: pkg=vim state=installed