- name: Install Shinken's storm supervisor services
  sudo_user: shinken
  template: src=storm-supervisor-service.cfg.j2 dest=/etc/shinken/services/storm-supervisor-service.cfg
  when: shinken_type == "server"
