#Include variables from file
- include_vars: "../../../profile/{{ profile_type | default('default') }}.yml"
  tags: 
    [ start, stop ]

- name: Stop resourcemanager Service
  service: name=hadoop-resourcemanager state=stopped enabled=no
  sudo: true
  when: ansible_virtualization_type != 'docker'
  tags:
  - stop
  
- name: Stop resourcemanager Service on docker
  shell: "{{ hadoop_master.software.installation.hadoop_home_dir }}/sbin/yarn-daemon.sh stop resourcemanager"
  when: ansible_virtualization_type == 'docker'
  tags:
  - stop

- name: Kill ResourceManager
  shell:  kill -9 $(jps -m | grep 'ResourceManager' | awk '{print $1}')
  ignore_errors: yes
  tags:
    - force-stop
      
- name: Start resourcemanager Service
  service: name=hadoop-resourcemanager state=started enabled=yes
  sudo: true
  when: ansible_virtualization_type != 'docker'
  tags:
  - start

- name: Start resourcemanager Service on docker
  shell: "{{ hadoop_master.software.installation.hadoop_home_dir }}/sbin/yarn-daemon.sh start resourcemanager"
  when: ansible_virtualization_type == 'docker'
  tags:
  - start
  