hadoop_home_dir: /opt/hadoop
hadoop_log_dir: /opt/hadoop/logs 
hadoop_tar: hadoop-2.7.1.tar.gz
hadoop_url: https://archive.apache.org/dist/hadoop/core/hadoop-2.7.1/hadoop-2.7.1.tar.gz

NAMENODE_HEAPSIZE: 1024
SECONDARYNAMENODE_HEAPSIZE: 1024
DATANODE_HEAPSIZE: 1024
YARN_RESOURCEMANAGER_HEAPSIZE: 1024
YARN_NODEMANAGER_HEAPSIZE: 1024
hadoop_tmp_dir: /opt/hadoop/data
fs_default_name: hdfs://hadoop-master:9000
hadoop_http_staticuser_user: neverwinterdp
dfs_replication: 3
yarn_resourcemanager_hostname: hadoop-master
yarn_nodemanager_hostname: 0.0.0.0
yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
yarn_nodemanager_resource_cpu_vcores: 4
yarn_nodemanager_resource_memory_mb: 2048
yarn_nodemanager_vmem_check_enabled: false
yarn_nodemanager_vmem_pmem_ratio: 2
yarn_scheduler_minimum_allocation_mb: 512
yarn_scheduler_minimum_allocation_vcores: 1
yarn_scheduler_maximum_allocation_vcores: 1
yarn_scheduler_capacity_resource_calculator: org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator
