- name: Check if Java is already isntalled
  stat: path=/usr/bin/java
  register: installed

- name: Install Java RPM
  yum: name=https://s3-us-west-2.amazonaws.com/nvent-repo/rpm/jdk/8u45/jdk-8u45-linux-x64.rpm state=present
  sudo: yes
  when: installed.stat.exists == false

