---
- name: Check if home dir is created
  stat: path=/opt/grafana/versions/{{ grafana_version }}
  register: installed

- name: Yum install Grafana
  yum: name=https://s3-us-west-2.amazonaws.com/nvent-repo/rpm/grafana/2.0.0/grafana-2.0.0_beta1-1.x86_64.rpm state=present
  sudo: yes
  when: installed.stat.exists == false
