webui_cfg_modules:
  - auth-cfg-password

broker_master_modules:
  - webui

generic_shinken_contact_email: dummy@placeholder.com


shinken_hosts:
  - host_name: localhost
    ip: 127.0.0.1
    contacts:
      - bdcoe

shinken_services:
  - host_names:
      - localhost
    contacts:
      - bdcoe
    services:
      - name: memory
        desc: check_memory
        cmd: check_memory_nrpe
        #max_check_attemtps: 5, #default
        #check_interval: 3, #default
        #retry_interval: 3, #default
        #
        #check_period: 24x7, #default
        #notification_interval: 30 #default
        #notification_period: 24x7 #default
      - name: load
        desc: check_load
        cmd: check_load_nrpe


