
- name: download influxdb (DEB file - Ubuntu)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  get_url: url=https://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb dest=/tmp/influxdb.deb


- name: install influxdb (Unbuntu)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  sudo: yes
  apt: deb=/tmp/influxdb.deb



- name: install influxdb from remote repo (CentOS)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  sudo: yes
  yum: name=https://s3.amazonaws.com/influxdb/influxdb-latest-1.x86_64.rpm state=present
  
  
- name: stop influxdb in case its already running
  sudo: yes
  command: /etc/init.d/influxdb stop
  
- name: start influxdb
  sudo: yes
  command: /etc/init.d/influxdb start