#Include variables from file
- include_vars: "../../../profile/{{ profile_type | default('default') }}.yml"
  tags: 
    [ start, stop ]

- name: Profile type
  local_action: debug msg="{{ profile_type | default('default') }}"
  run_once: true
  tags: [ configure, install, clean, start, stop, force-stop ]

- name: Stop nodemanager Service
  service: name=hadoop-nodemanager state=stopped enabled=no
  sudo: true
  when: ansible_virtualization_type != 'docker'
  tags:
  - stop

- name: Stop nodemanager Service on docker
  shell: "{{ hadoop_master.software.installation.hadoop_home_dir }}/sbin/yarn-daemon.sh stop nodemanager"
  when: ansible_virtualization_type == 'docker'
  tags:
  - stop
  
- name: Kill NodeManager
  shell:  kill -9 $(jps -m | grep 'NodeManager' | awk '{print $1}')
  ignore_errors: yes
  tags:
    - force-stop
    
- name: Start nodemanager Service
  service: name=hadoop-nodemanager state=started enabled=yes
  sudo: true
  when: ansible_virtualization_type != 'docker'
  tags:
  - start

- name: Start nodemanager Service on docker
  shell: "{{ hadoop_master.software.installation.hadoop_home_dir }}/sbin/yarn-daemon.sh start nodemanager"
  when: ansible_virtualization_type == 'docker'
  tags:
  - start
  