- name: Install necessary yum packages
  yum: name={{item}} state=installed
  sudo: yes
  with_items:
    - python-pycurl
    - python-setuptools
    - python-pip

- name: install shinken
  sudo: yes
  pip: name=shinken state=present

- name: initialize shinken cli
  sudo_user: shinken
  shell: "shinken --init"

- name: Is shinken's webui module installed
  stat: path=/var/lib/shinken/modules/webui
  register: webui_is_installed
  sudo: yes

- name: Is shinken's auth-cfg-password module installed
  stat: path=/var/lib/shinken/modules/auth-cfg-password
  register: auth_cfg_password_is_installed
  sudo: yes

- debug: var=webui_is_installed
- debug: var=auth_cfg_password_is_installed

- name: install shinken's webui modules
  sudo_user: shinken
  shell: "shinken install {{item}}"
  with_items:
    - webui
  when:
    webui_is_installed.stat.exists == False

- name: install shinken's auth-cfg-password modules
  sudo_user: shinken
  shell: "shinken install {{item}}"
  with_items:
    - auth-cfg-password
  when:
    auth_cfg_password_is_installed.stat.exists == False

- template: src={{item}}.j2 dest=/etc/shinken/modules/{{item}}
  sudo_user: shinken
  with_items:
    - webui.cfg

- template: src={{item}}.j2 dest=/etc/shinken/brokers/{{item}}
  sudo_user: shinken
  with_items:
    - broker-master.cfg

- name: Ensure that shinken is running after reboot
  sudo: yes
  shell: /sbin/chkconfig shinken on

- name: Install shinken's command config files
  sudo_user: shinken
  copy: src={{item}} dest=/etc/shinken/commands/{{item}} mode=0644 owner=shinken group=shinken
  with_items:
    - check_disk_nrpe.cfg
    - check_memory_nrpe.cfg
    - check_total_procs_nrpe.cfg
    - check_zombie_procs_nrpe.cfg
    - check_users_nrpe.cfg
    - check_load_nrpe.cfg

- name: Install Shinken's contact config file
  sudo_user: shinken
  template: src={{item}}.j2 dest=/etc/shinken/contacts/{{item}}
  with_items:
    - bdcoe.cfg

- include: register_all_hosts.yml

- include: register_all_services.yml

- name: run shinken
  sudo: yes
  service: name=shinken state=started
