---
- name: Installs and configures the tier 1 layer of Odyssey
  hosts: 'gripper'
  remote_user: 'centos'
  roles:
    - { role: 'gripper', kafka_conn_string: "{{ groups['tier2-kafka-broker']|join(':9092,') }}:9092" }

