---
- name: Installs and configures the gripper of Odyssey
  hosts: 'gripper'
  remote_user: 'centos'
  roles:
    - { role: 'gripper', kafka_conn_string: "{{ groups['kafka-broker']|join(':9092,') }}:9092" }

