---
# Installs and configures the odyssey-monitoring layer of Odyssey

- name: Installs and configures Elasticsearch
  hosts: odyssey-monitoring
  remote_user: centos
  roles:
    - odyssey_elasticsearch
