- name:  Disable strict host key checking in ssh
  lineinfile: dest=~/.ssh/config
              line='StrictHostKeyChecking no'
              state=present
              create=yes
              mode=600
  tags: [install]

- name: Change mode for ~/.python-eggs to g-wx,o-wx
  file: mode=g-wx,o-wx path=~/.python-eggs state=directory
  tags: [install]
